language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn scm:checkout -Dmodule.name=entity-extractor
  - cd entity-extractor
  - mvn clean install
  - cd ..
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh